name: Build and Release Spring Boot Jar

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build Jar
        run: mvn clean package

      - name: Delete Existing Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
